# Basic
title = "Vno Hugo"
baseURL = "http://vno.onevcat.com"
theme="vno-hugo"

welcome_message = "Oh What a World"

#Format
highlighter = "rouge"

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color = "red"

# Pagination
paginate = 10
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[params]
author = "onevcat"
subtitle = "A blog-orientation theme for Hugo"
description = "Vno Hugo is a port of Vno Jekyll."

[permalinks]
post = "/:year/:month/:title/"

# The blog button should not be removed.
[blog_button]
title = "Blog"
description = "Visit blog"

nav = [
  #{title = "Projects", description = "My Projects", url = "http://project.onevcat.com"},
  {title = "Projects", description = "My Projects", url = "http://project.onevcat.com"}
]

[comment]
disqus = "vno-jekyll"
duoshuo = ""

[taxonomies]
  tag = "tags"


[social]
weibo = "onevcat"
github = "onevcat"
twitter = "onevcat"
gplus = "107108267983477358170"
mail = "onev@onevcat.com"

# Google Analytics
[ga]
id = "your_ga_id"
host = "your_host"
